name: Test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: ge9/actions-playground/.github/actions/tailscale@main
        with: 
          oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}