name: Matrix Test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: ge9/actions-playground/.github/actions/tailscale@main
        with: 
          oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
      - name: test
        shell: bash
        run: |
          which go || true
      - name: gha-shell
        shell: bash
        run: |
          PWD_BAK="$PWD"
          cd ~
          export -p | sed 's/^\(declare -x \([^=]*\)=.*\)$/if [ -z "$\2" ]; then\necho set \2 \n\1\nfi/' > gha-shell
          echo cd "$PWD_BAK" >> gha-shell
          echo exec ${{ runner.os == 'Windows' && 'cmd' || '\$SHELL -l' }} >> gha-shell
          chmod +x gha-shell
      - name: gha-shell.bat
        if: runner.os == 'Windows'
        run: echo "bash %USERPROFILE%\gha-shell" > $env:USERPROFILE\gha-shell.bat
